### ISSUE TITLE
code cleanup: unused file intercom/events.py

### ISSUE THREAD

**Issue by cezio** [jkeyes/python-intercom#104]
It seems that https://github.com/jkeyes/python-intercom/blob/master/intercom/events.py is not used anywhere, it defines class already defined in https://github.com/jkeyes/python-intercom/blob/master/intercom/event.py

**Comment by jkeyes** [comment]
@cezio Thanks for pointing that out. Events is an old implementation.

**Comment by jkeyes** [comment]
3.0b3 now on [PyPi](https://pypi.python.org/pypi/python-intercom).
