### ISSUE TITLE
SSLError - EOF occurred in violation of protocol (_ssl.c:600)

### ISSUE THREAD

**Issue by DevilPinky** [jkeyes/python-intercom#105]
It seems that this module uses `certifi` and it fails...sometimes.
In 75% request to Intercom API fails with this error and it's weird that it's not 100%:

> **Type** SSLError
> **Value** EOF occurred in violation of protocol (_ssl.c:600)
> **Module** requests.exceptions
> **Location** requests/adapters.py, send:431

I also had a problem with other external packages, once I started using this one. The problem was this:

> **Type** SSLError
> **Value** [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
> **Module** requests.exceptions
> **Location** requests/adapters.py, send:433

But I find workaround for this one, I simply replaced `certifi` certificate with `requests` certificate.

**Comment by jkeyes** [comment]
@DevilPinky `requests` uses `certifi` if it can. It's a preferred method to obtain a cert as the one shipped with `requests` only gets updated with each release. See https://github.com/kennethreitz/requests/blob/master/requests/certs.py for how `requests` handles this

With regards to the failure, is this consistently reproducible by you?
