### ISSUE TITLE
Support for contacts/leads

### ISSUE THREAD

**Issue by vpontis** [jkeyes/python-intercom#109]
Is support for contacts/leads coming? That would be really helpful! 

I'd love to use this to convert leads to users programmatically. This isn't easy to do within the Intercom UI.

**Comment by jkeyes** [comment]
@vpontis will get to this. Thanks.

**Comment by santiagomalter** [comment]
:+1:

**Comment by yacobell** [comment]
:+1:

**Comment by jkeyes** [comment]
Added support to version-3 branch.

**Comment by jt-money** [comment]
@jkeyes any chance of this awesome addition making it to version 2.1.1? Or do we have to update to 3? Also, any chance we can get "python-intercom3" added to pip? I only see versions 0.2 - 2.1.1 available:

> $ pip install python-intercom==3
Collecting python-intercom==3
  Could not find a version that satisfies the requirement python-intercom==3 (from versions: 0.2.0, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 2.0a0, 2.0b0, 2.0.0, 2.1.0, 2.1.1)
No matching distribution found for python-intercom==3

**Comment by jkeyes** [comment]
3.0b3 now on [PyPi](https://pypi.python.org/pypi/python-intercom).
