### ISSUE TITLE
ImportError: cannot import name User

### ISSUE THREAD

**Issue by gasparmrb** [jkeyes/python-intercom#110]
Hi,
I had installed Python-Intercom, but it's don't work....

![image](https://cloud.githubusercontent.com/assets/7880188/13437207/e871fbd0-dfda-11e5-8ead-36202ad5e70b.png)

My code is:

import intercom
from intercom import User

intercom.app_id = "..."
intercom.app_api_key = "..."

for user in User.all():
    print user
    
    
But I obtain the following error:

![image](https://cloud.githubusercontent.com/assets/7880188/13437245/1ae40aa4-dfdb-11e5-9daa-44a9b21c405d.png)

Can you help me, please?

**Comment by jfeldstein** [comment]
What was the fix for this? I am having the same issue today.

**Comment by jfeldstein** [comment]
I was calling it from a file called `intercom` which caused a circ dependenciy
