### ISSUE TITLE
API errors don't raise exception

### ISSUE THREAD

**Issue by hheimbuerger** [jkeyes/python-intercom#116]
I'm calling `User.create()` on v2.1.1 and apparently I got some encoding wrong. However, python-intercom does not raise an exception, which makes this almost impossible to detect without reviewing the logs.

Example log (values anonymized):

```
[03/Jun/2016 15:43:58] DEBUG [Web/intercom.request] Sending POST request to: https://api.intercom.io/users/
[03/Jun/2016 15:43:58] DEBUG [Web/intercom.request]   headers: {'content-type': 'application/json', 'Accept': 'application/json', 'User-Agent': 'python-intercom/2.1.1'}
[03/Jun/2016 15:43:58] DEBUG [Web/intercom.request]   params: {"user_id": 1, "name": "X M\u00f8x"}
{'detail': 1, 'name': u'X M\xf8x'}
[03/Jun/2016 15:43:59] DEBUG [Web/intercom.request] Response received from https://api.intercom.io/users/
[03/Jun/2016 15:43:59] DEBUG [Web/intercom.request]   encoding=utf-8 status:200
Traceback (most recent call last):
  File "C:\Python\2.7\lib\logging\__init__.py", line 859, in emit
    msg = self.format(record)
  File "C:\Python\2.7\lib\logging\__init__.py", line 732, in format
    return fmt.format(record)
  File "C:\Python\2.7\lib\logging\__init__.py", line 474, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 139: ordinal not in range(128)
Logged from file request.py, line 54
```

Expected behavior: an exception to be raised in this case.

**Comment by hheimbuerger** [comment]
On second look, this seems to be purely a logging problem. Interesting.

Don't think I have any particularly special logging configuration in this regard. Definitely haven't had any issues so far with logging unicode.

**Comment by jkeyes** [comment]
Any further detail on this @hheimbuerger? I'm not going to do anymore work on v2, have you tried in v3 to see if it's still an issue? https://github.com/jkeyes/python-intercom/tree/version-3

**Comment by hheimbuerger** [comment]
@jkeyes I haven't tested in v3 yet.

Have you tried creating a User with some crazy encoding (my usual test string is "℉ḯяß⊥ηαмê ℒ@ç☂ηàღë"), while logging is enabled, so that you get the JSON request and response replicated to stdout?

**Comment by jkeyes** [comment]
@hheimbuerger I haven't tested with names like that. I'll do so now.

**Comment by jkeyes** [comment]
I've tested the following with version-3:

```python
>>> from intercom.client  import Client
>>> token = '...'
>>> client = Client(token)
>>> client.users.create(email='john@example.com', user_id='jexam', name='℉ḯяß⊥ηαмê ℒ@ç☂ηàღë')
<intercom.user.User object at 0x7fbb85a208d0>
>>> user = client.users.find(email='john@example.com')
>>> user
<intercom.user.User object at 0x7fbb85a20dd0>
>>> user.name
u'\u2109\u1e2f\u044f\xdf\u22a5\u03b7\u03b1\u043c\xea \u2112@\xe7\u2602\u03b7\xe0\u10e6\xeb'
>>> print unicode(user.name)
℉ḯяß⊥ηαмê ℒ@ç☂ηàღë
```

**Comment by deadfrominside** [comment]
This is caused by [request.py:82](https://github.com/intercom/python-intercom/blob/2e15c3ecb416d4ff693284745d8bde5014388807/intercom/request.py#L82)
Which tries to log python2 string which might contain non ascii characters, which would cause logger to log this UnicodeDecodeError.
