### ISSUE TITLE
Dynamic credentials

### ISSUE THREAD

**Issue by jpocentek** [jkeyes/python-intercom#117]
Is it possible to use this package with different credentials for every request? It seem to get global configuration and it's impossible to change it at runtime. For example I'm trying to create function that will fetch data from given account, something like this:

```
@shared_task
def get_intercom_user(email=None, api_id=None, api_key=None):
    if api_id is None or api_key is None:
        raise ImproperlyConfigured("Intercom api keys required")
    elif email is None:
        raise Exception("An email address is required")
    Intercom.app_id = api_id
    Intercom.app_api_key = api_key
    return User.find(email=email)
```

And I get `AuthenticationError: Unauthorized` error. It's Django implementation and it's working if settings are taken from config file during application startup, but not when they are passed dynamically into function in any way (or Celery task, it is only one of many tries).

**Comment by jkeyes** [comment]
In v3 you can use different credential by instantiating a new client per request. See https://github.com/jkeyes/python-intercom/tree/version-3 docs.

**Comment by jkeyes** [comment]
3.0b3 now on [PyPi](https://pypi.python.org/pypi/python-intercom).
