### ISSUE TITLE
Unable to use python-intercom with oauth token

### ISSUE THREAD

**Issue by ankurrawal** [jkeyes/python-intercom#118]
Hi , 
i am unable to use this library with oauth token, Can you point the documentation for the same ?

**Comment by jkeyes** [comment]
There is no support for OAuth in v2 or v3. I haven't looked into supporting it yet.

**Comment by bnjix** [comment]
Hi @jkeyes, 
Any timeframe on supporting access tokens ?
Correct me if I'm wrong, but I think Intercom will drop api key support next month (see here https://developers.intercom.com/reference#personal-access-tokens-1)
Thanks

**Comment by jkeyes** [comment]
Hi @bnjix, access token support is in v3 beta (`
pip install python-intercom==3.0b3`).

**Comment by ankurrawal** [comment]
Ok Thanks

**Comment by jkeyes** [comment]
@ankurrawal Version 3 (current is 3.1.0) supports personal access tokens. I have no plans to introduce any features to aid the OAuth flow, but the OAuth token should no work by passing it to the client:

```
oauth_token = '...'
client = Client(oauth_token)
```

Please test and let me know if it's working for you. Thanks.
