### ISSUE TITLE
Support for personal access tokens?

### ISSUE THREAD

**Issue by rsaftoiu** [jkeyes/python-intercom#122]
Just got a message from intercom that api tokens will no longer be accepted as of Jan 27th, 2017 - is there a plan to support their new personal access tokens ?See: https://developers.intercom.io/v2.0/docs/personal-access-tokens

**Comment by jkeyes** [comment]
Yes, we'll need to add support for this.

**Comment by frankie567** [comment]
Meanwhile, a "hacky" way to authenticate with Personal Access Tokens is  to set the `app_id` to the token and the `app_api_key` to an empty string. Check the [curl example on the Intercom doc](https://developers.intercom.com/v2.0/docs/personal-access-tokens#section-using-personal-access-tokens) to understand why.

**Comment by jangnezda** [comment]
For anyone wondering, @frankie567 's suggestion works also for OAuth tokens.

**Comment by lizmallalieu** [comment]
Just ran into this issue - the "hacky" way works for now but it would be great to get support for this!

**Comment by frankie567** [comment]
I proposed PR #123 for this, ready to be merged!

**Comment by jkeyes** [comment]
I've had a look at @frankie567 PR, this will be supported very soon in version-3. I'll update here when it's merged.

**Comment by jkeyes** [comment]
version-3 now has personal access token support.

**Comment by jkeyes** [comment]
3.0b3 now on [PyPi](https://pypi.python.org/pypi/python-intercom).
