### ISSUE TITLE
Support for scroll api?

### ISSUE THREAD

**Issue by ubaldo** [jkeyes/python-intercom#126]
User listing only works for up to 10k users. I realize that the scroll api is in beta but I wonder if it has been considered

**Comment by jkeyes** [comment]
@ubaldo not yet. 3.1 release I'd say.

**Comment by jkeyes** [comment]
@ubaldo I've added support for the Scroll API: https://github.com/jkeyes/python-intercom/pull/156 It's available in the 3.1.0 release.
