### ISSUE TITLE
http://keyes.ie/things/python-intercom/ expired certificate

### ISSUE THREAD

**Issue by centralniak** [jkeyes/python-intercom#127]
Minor issue but I think it'd be good to update the link in the github description of this project as it points to a site with an expired SSL cert.

**Comment by jkeyes** [comment]
Ah cool. I keep saying today, and then tomorrow. Thanks for letting me know.

On Tue, Nov 15, 2016 at 14:26, Piotr Kilczuk <notifications@github.com> wrote:
Minor issue but I think it'd be good to update the link in the github description of this project as it points to a site with an expired SSL cert.

**Comment by jkeyes** [comment]
I had the certs updated but the webserver wasn't restarted. All good now.
