### ISSUE TITLE
How do I fetch a conversation in JSON format ? When using json.dumps, it gives me an error saying "object is not JSON serializable"

### ISSUE THREAD

**Issue by akshayrpatel** [jkeyes/python-intercom#144]

**Comment by jkeyes** [comment]
@akshayrpatel You can call `Conversation.to_dict()` to access the raw data.

**Comment by akshayrpatel** [comment]
Yes, to_dict() works. But what if the returned conversation is a nested JSON ?

**Comment by jkeyes** [comment]
@akshayrpatel I don't see the distinction being honest. Can you give me a concrete example of when `to_dict()` doesn't provide the functionality you need?

However, you can always drop to a lower level and do something along the lines of this if you really need to:

```
from intercom import request
pat = "<personal access token">
params = {"type": "user", "user_id": "your_username"}
req = request.Request('GET', '/conversations')
result = request.execute('https://api.intercom.io', (pat, ''), params)
# result is a dict
```
