### ISSUE TITLE
User deletion doesn't work

### ISSUE THREAD

**Issue by bachle** [jkeyes/python-intercom#145]
Version **3.0b3**

Following the docs for deleting a user doesn't seem to work: 

`deleted_user = intercom.users.find(user_id="1").delete()
`

Results in this error message

> AttributeError: 'User' object has no attribute 'delete'

The traceback says this: 

> Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/fedora/deploy/master/lib/python2.7/site-packages/intercom/traits/api_resource.py", line 98, in __getattribute__
    value = super(Resource, self).__getattribute__(attribute)

The get request for the find call does seem to work:

> send: 'GET /users?user_id=1 HTTP/1.1\r\nHost: api.intercom.io\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/json\r\nUser-Agent: python-intercom/3.0b3\r\nAcceptEncoding: gzip, deflate
reply: 'HTTP/1.1 200 OK\r\n'

**Comment by jkeyes** [comment]
@bachle The documentation is out of date. The version 3 way of doing this is by calling `delete` on `Client` rather than the resource itself:

```
from intercom.client import Client
client = Client(personal_access_token="abc")
# Delete a user
user = client.users.find(user_id="1")
deleted_user = client.users.delete(user)
```

I'll update the docs.

**Comment by jkeyes** [comment]
Docs are now updated: http://python-intercom.readthedocs.io/en/latest/

Thanks @bachle 👍
