### ISSUE TITLE
Invalid import

### ISSUE THREAD

**Issue by ubaldo** [jkeyes/python-intercom#149]
#I believe that this import will fail. 
from intercom import Intercom

Looks like some piece of code that wasn't properly migrated

https://github.com/jkeyes/python-intercom/blob/master/intercom/api_operations/count.py#L13

**Comment by jkeyes** [comment]
@ubaldo Not sure how that slipped through, but yeah it looks wrong, should be using the client. Thanks for letting me know.

**Comment by jkeyes** [comment]
@ubaldo actually that module shouldn't exist anymore, as the functionality is provided by `client.counts`. Removed as part of https://github.com/jkeyes/python-intercom/pull/152.
