### ISSUE TITLE
ReadTimeout error

### ISSUE THREAD

**Issue by helpingharry** [jkeyes/python-intercom#150]
Hi there, I had this set up to pull all tags from our Intercom and then make a CSV with them, this was before the change to the personal access tokens and just using the API keys. I have since updated everything to use the PAT, but I am now getting the below error.

`ReadTimeout: HTTPSConnectionPool(host='api.intercom.io', port=443): Read timed out. (read timeout=10)`

Could this be because we have so many tags? I am working in a Jupyter notebook and the used code is below:

```
from intercom.client import Client

import unicodecsv
import time

intercom = Client(personal_access_token='xxx')

def get_tag_count():
  tags_count = intercom.counts.for_type(type='user', count='tag').attributes
  timestr = time.strftime('%Y%m%d')
  csv_filename = 'tags-report-{}.csv'.format(timestr)
  outputFile = open(csv_filename, 'w')
  outputWriter = unicodecsv.writer(outputFile)
  for obj in tags_count:
    row = obj.items()[0]
    
    outputWriter.writerow(row)
    print row

  outputFile.close()
#   print tags_count

# Kick things off
get_tag_count()
```

Any advice that can be offered by you is very much appreciated.

All the best, Harry

**Comment by jkeyes** [comment]
@helpingharry It's nothing to do with PAT, just that the `count` requests takes longer with a lot of tags. 3.0.5 has been released, in which the default timeout has been increased from 10 to 90 seconds (same as the intercom-ruby lib) and it can be set from the environment via `INTERCOM_REQUEST_TIMEOUT`. See #154.

**Comment by helpingharry** [comment]
Hi there, thanks for getting in touch with me and informing me about the update. I I am unfortunately now receiving a new error. The error is `---------------------------------------------------------------------------
HttpError                                 Traceback (most recent call last)
<ipython-input-27-a1c2af1c843e> in <module>()
     39 # get_tag_count()
     40 
---> 41 print (intercom.counts.for_type(type='user', count='tag').attributes)

/usr/local/lib/python2.7/site-packages/intercom/service/count.pyc in for_type(self, type, count)
     16 
     17     def for_type(self, type, count=None):
---> 18         return self.find(type=type, count=count)

/usr/local/lib/python2.7/site-packages/intercom/api_operations/find.pyc in find(self, **params)
     20 
     21         if response is None:
---> 22             raise HttpError('Http Error - No response entity returned')
     23 
     24         return self.collection_class(**response)

HttpError: Http Error - No response entity returned
`
The code I am trying to run now is:

`from intercom.client import Client
import unicodecsv
import time
intercom = Client(personal_access_token='dG9rOjQwYTQ1OGUwXzI1MjNfNDJmZl9iOTNlXzU1MGRmYjJjNjJiNzoxOjA=')

print (intercom.counts.for_type(type='user', count='tag').attributes)`

Weirdly if I change type  to company I get the expected list of json data.

Any help you can offer is much appreciated.

Best, Harry

**Comment by jkeyes** [comment]
@helpingharry I've deleted your personal access token from the code samples, you should keep it private, and I'd recommend you create a new one for your app.

I think you need to get in touch with Intercom directly, as this is now something that's beyond this project's scope. To validate you can test with `cURL` and e.g.

```
curl 'https://api.intercom.io/counts?type=user&count=tag' -u :<PAT> -H 'Accept:application/json'
```

If that works then there is an issue with `python-intercom`, otherwise it's a problem with the Intercom API itself.

**Comment by teeberg** [comment]
I still see a PAT in the last comment

**Comment by helpingharry** [comment]
Oh right yeah. Thanks very much for pointing that out. Sorry. Ok cool,
 I'll try and access it via curl and see how that goes.

Cheers
