### ISSUE TITLE
Determine whether ConversationPart.author is User or Admin

### ISSUE THREAD

**Issue by eliorc** [jkeyes/python-intercom#151]
I need to understand in runtime, if a certain `ConversationPart`'s author is a User or an Admin.

Lets say I have `conv_part` which is a `ConversationPart` after applying `to_dict()` on it, now when I'll execute `type(conv_part['author'])` I'll see `<intercom.utils.Admin object at 0x1ae9038>` something like that.
So I tried two options, using `isinstance(conv_part['author'], intercom.utils.Admin)` which gives me an error because `intercom.utils` indeed does not include that class and I've tried `from intercom.admin import Admin \ isinstance(conv_part['author'], Admin)` which returns `False`, even though it is an admin.

Currently I solve this by getting `__class__.__name__` and comparing it to a string.. but that is not the elegant solution I'm looking for.

So how can I determine in runtime which object is the author?

**Comment by jkeyes** [comment]
@eliorc 3.0.4 has added a `resource_type` attribute to the lightweight classes: `conv_part.author.resource_type` will now return `admin` or `user` depending on the resource at the time.
