### ISSUE TITLE
Cannot use language_override

### ISSUE THREAD

**Issue by k4rl85** [jkeyes/python-intercom#163]
I'm trying to change the field `language_override` for my users but it seems it is not supported by python api.
It should be a "standard" field but the api does not have it, I have tried with custom attributes with no success.

If i try to change it with javascript api it change correctly. Any suggestion?

Carlo

**Comment by tanasegabriel** [comment]
The `language_override` attribute is specific to the JS API and it is not exposed through the REST API.

https://developers.intercom.com/v2.0/reference#user-model

**Comment by jkeyes** [comment]
@tanasegabriel is correct. Closing.
