### ISSUE TITLE
High level support for `Company`

### ISSUE THREAD

**Issue by kracekumar** [jkeyes/python-intercom#29]
Intercom supports high level API to query company. Docs are available at `http://doc.intercom.io/api/#companies`. 

Here is a python example for it, http://doc.intercom.io/api/#view-a-company.

```
In [43]: intercom.Intercom._call('GET', intercom.Intercom.api_endpoint + 'companies', params={'id': 1})
Out[43]:
{u'created_at': 1410530757,
 u'custom_data': {},
 u'id': u'1',
 u'monthly_spend': 18,
 u'name': u'\u0627\u0633\u0645 \u0627\u0644\u0634\u0631\u0643\u06296',
 u'plan': u'4'}
```

Add a new `Company` class which can perform various operation. If ok, I can send pull request.

**Comment by jkeyes** [comment]
@kracekumar I've gotten through some stuff in the past week on the apiv2 branch and I think it's very close now.

**Comment by jkeyes** [comment]
Company support in `apiv2`.

**Comment by kracekumar** [comment]
Thanks!

**Comment by jkeyes** [comment]
@kracekumar This is now in the 2.0.alpha release on PyPI if you want to try it out. The `apiv2` branch has been deleted.
