### ISSUE TITLE
ResourceNotFound error

### ISSUE THREAD

**Issue by skunkwerk** [jkeyes/python-intercom#44]
Hi John,

thanks for putting together this library for our use.
Do you know what this error means?  I try the same call from my console, and I don't get any error - so I'm not sure what's causing this.

File "/src/index.py", line 399, in send_event_to_intercom
    impression = Event.create(event_name=event, user_id=customer_id, metadata=properties)
  File "intercom/events.py", line 17, in create
    resp = Intercom.create_event(event_name=event_name, user_id=user_id, email=email, metadata=metadata)
  File "intercom/intercom.py", line 463, in create_event
    'POST', Intercom.api_endpoint + 'events', params=params)
  File "intercom/intercom.py", line 66, in wrapper
    raise_errors_on_failure(response)
  File "intercom/intercom.py", line 76, in raise_errors_on_failure
    raise ResourceNotFound("Not found.")

**Comment by snario** [comment]
:+1:

**Comment by jkeyes** [comment]
@skunkwerk @snario Have you tried this with the latest code on the apiv2 branch? (Sorry for being so very late in replying)

**Comment by jkeyes** [comment]
@skunkwerk @snario Version 2.0.alpha has been released: https://pypi.python.org/pypi/python-intercom/2.0.alpha Let me know if you still encounter the problem.

**Comment by greenafrican** [comment]
Hi @jkeyes I'm using the newly merged master and am receiving this error.

**Comment by jkeyes** [comment]
Hey @greenafrican. Please include some example code that reproduces the problem, and I'll take a look.

**Comment by greenafrican** [comment]
Pretty basic:
```
pip install python-intercom==2.0.alpha

from intercom import Intercom
Intercom.app_id = 'xxx'
Intercom.app_api_key = 'xxx'
from intercom import User
user = User.find(email="bob@example.com")

...    
     69     def raise_errors_on_failure(cls, resp):
     70         if resp.status_code == 404:
---> 71             raise errors.ResourceNotFound('Resource Not Found')
     72         elif resp.status_code == 401:
     73             raise errors.AuthenticationError('Unauthorized')

ResourceNotFound: Resource Not Found```

**Comment by jkeyes** [comment]
@greenafrican If 'bob@example.com' isn't a user in your app then that error is expected.

**Comment by greenafrican** [comment]
A `404`? Usually expect that with broken links. Oops. I expected the response to still be successful but empty or null. Thanks

**Comment by jkeyes** [comment]
Yeah. The 404 status code indicates that what was requested could not be found. In the case of this call what is being requested is an `application/json` representation of a `User`.

**Comment by greenafrican** [comment]
Ok cool. I thought `resource` was referring to the server. Perhaps change the example to:

```user = User.create(email="bob@example.com", name="Bob Smith")
user = User.find(email="bob@example.com")```

;)

Thanks for the stellar work!
