### ISSUE TITLE
Session count not incrementing

### ISSUE THREAD

**Issue by grantmcconnaughey** [jkeyes/python-intercom#73]
I am unable to increment the session count for a user. I have tried the following:

This one just doesn't do anything:
```
user.increment("sessions")
```

This creates a new attribute in Intercom called "session_count":
```
user.increment("session_count")
```

Any ideas?

**Comment by jkeyes** [comment]
The following is the increment test from the integration tests:

    def test_increment(self):
        # Perform incrementing
        user = User.find(id=self.user.id)
        karma = user.custom_attributes.get('karma', 0)
        user.increment('karma')
        user.save()
        self.assertEqual(user.custom_attributes["karma"], karma + 1)
        user.increment('karma')
        user.save()
        self.assertEqual(user.custom_attributes["karma"], karma + 2)

To modify the session count I think you have to update the user, and pass the `new_session` attribute. The following is from the [Intercom API docs](https://doc.intercom.io/api/#create-or-update-user):

    new_session        no        A boolean value, which if true, instructs Intercom  
                                 to register the request as a session.

I haven't tested that, let me know if it works.

**Comment by grantmcconnaughey** [comment]
Thanks for the help. That did work. Here's what I did:

```
user = User.find(email=email)
user.last_request_at = time.time()
user.new_session = True
user.save()
```

**Comment by jkeyes** [comment]
Excellent. I'll put together an integration test based on these types of scenarios and an accompanying page in the docs to show examples.

**Comment by jkeyes** [comment]
I've asked Intercom about this. I've tried running the following cURL command multiple times and the session count remains the same:

    curl https://api.intercom.io/users \
    -X POST \
    -u xxx:xxx \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' -d '
    {
      "email": "me@example.com",
      "new_session": true
    }'

**Comment by grantmcconnaughey** [comment]
Weird. Surely `last_request_at` isn't required to update the session count. Have you tried adding that as well? I've successfully gotten the session count to update several times with the code above.

**Comment by jkeyes** [comment]
It seems like there was glitch on the Intercom side. The cURL commands are working for me now. I've added `test_73.py` to highlight the usage.
