### ISSUE TITLE
no valid example provided

### ISSUE THREAD

**Issue by timredfern** [jkeyes/python-intercom#89]
might be an idea to provide a complete working example?

I'm sure it should be obvious, but I'm trying this:

>>> import intercom
>>> intercom.Intercom.app_id = "MYAPPID"
>>> intercom.Intercom.app_api_key = "MYAPPKEY"
>>> intercom.User.find(email="MYEMAIL")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/intercom/user.py", line 69, in find
    resp = Intercom.get_user(user_id=user_id, email=email)
  File "/Library/Python/2.7/site-packages/intercom/intercom.py", line 173, in get_user
    'GET', Intercom.api_endpoint + 'users', params=params)
  File "/Library/Python/2.7/site-packages/intercom/intercom.py", line 66, in wrapper
    raise_errors_on_failure(response)
  File "/Library/Python/2.7/site-packages/intercom/intercom.py", line 78, in raise_errors_on_failure
    raise AuthenticationError("Invalid API key/username provided.")
intercom.intercom.AuthenticationError: Invalid API key/username provided.
>>>

**Comment by timredfern** [comment]
has intercom changed the format of app and user IDs that they publish? failing the unit tests with 'Unauthorized"

**Comment by jkeyes** [comment]
@timredfern You are running the old version of python-intercom (check `pip freeze` output). To install the latest run `pip install python-intercom==2.0.beta`.

**Comment by mkemka** [comment]
@jkeyes have updated to the 2.0.beta but cannot run the User update example either:

me = User.find(email="internet@gmail.com")
me.custom_attribute["average_monthly_spend"] = 1234.56
me.save()

AttributeError: 'User' object has no attribute 'custom_attribute'

**Comment by jkeyes** [comment]
There is no `custom_attribute` attribute, it's `custom_attributes`.

Good examples of user operations here: https://github.com/jkeyes/python-intercom/blob/master/tests/integration/test_user.py

To see what attributes you can you can always do `dir(user)`.

**Comment by felixcheruiyot** [comment]
I have this problem too and I'm running v2.0.beta and I get unauthorized error.
