### ISSUE TITLE
Can not inherit from resource classes

### ISSUE THREAD

**Issue by teeberg** [jkeyes/python-intercom#94]
The current design deduces the API endpoints from the class name. If you want to inherit from a Resource class to give it more functionality, this screws up the API endpoint "computation". I think it would be nicer to specify the endpoint name directly as an attribute of the class instead of deriving it. In the spirit of [The Zen of Python](https://www.python.org/dev/peps/pep-0020/):

> Explicit is better than implicit.

and

> In the face of ambiguity, refuse the temptation to guess.

Have you thought about this? What do you think?

**Comment by jkeyes** [comment]
I hadn't thought about this. One of my goals for `python-intercom` was to mirror the code from `intercom-ruby` as much as possible. That was where I took the naming structure from.

**Comment by teeberg** [comment]
So I take `intercom-ruby` also infers the endpoint from the class name? What do you think about adding an explicit `type` or `resource` attribute to all `Resources`? That would be an easy fix, make it more explicit and allow subclassing.

**Comment by jkeyes** [comment]
'easy fix' - I think you'll find that in the 'famous last words' category
;)  You can put together a PR if you like and I'll review the changes.

**Comment by teeberg** [comment]
:D I don't have too strong feelings about it. I ended up not inheriting it and making an extra function that constructs the `Company` from an internal model. Feel free to close if you don't mind, I just thought I'd bring it up ;)
