### ISSUE TITLE
Support bulk user creation

### ISSUE THREAD

**Issue by teeberg** [jkeyes/python-intercom#96]
The v2 API allows bulk creation of users as specified here:
https://doc.intercom.io/api/#bulk-user-creation

It would be nice if python-intercom would support that! :-) I'll hack my way around it for now.

**Comment by catskul** [comment]
+1

**Comment by jkeyes** [comment]
@teeberg @catskul @arjunbanker This will be landing soon in the version-3 branch.

**Comment by jkeyes** [comment]
Support now in version-3 branch. I won't close this until I release v3.

**Comment by ashchristopher** [comment]
@jkeyes Do you have an ETA on when v3 will land?

**Comment by jkeyes** [comment]
@ashchristopher I'm working on it right now. (_eventually!_)

**Comment by jkeyes** [comment]
3.0b3 now on [PyPi](https://pypi.python.org/pypi/python-intercom).
