### ISSUE TITLE
Timout for operations.

### ISSUE THREAD

**Issue by psihonavt** [jkeyes/python-intercom#99]
Is there a way to set timeout for any operation (http request)? Potentially Intercom API can be down or slow due to some reasons and ideally I would like to control how much time requests can wait for it.

**Comment by jkeyes** [comment]
@psihonavt You can modify the value by setting `intercom.Request.timeout`. I added a test  2c1ea37d784333f70767c0b44ab03e989abdde20 to show it's use.
